POST http://localhost:3333/events
Content-Type: application/json

{
    "title": "Unite Summit", 
    "details": "Um evento para quem é apaixonado por programação",
    "maximumAttendees": 100
}

###

POST http://localhost:3333/events/a029f5c4-83ff-4f36-ad48-a66a60921d5f/attendees
Content-Type: application/json

{
  "name": "Victor Hugo",
  "email": "Victorhugo20santos@gmail.com"
}

###

GET http://localhost:3333/events/a029f5c4-83ff-4f36-ad48-a66a60921d5f

###

GET http://localhost:3333/attendees/1/badge

###

GET http://localhost:3333/attendees/1/check-in

###

GET http://localhost:3333/events/a029f5c4-83ff-4f36-ad48-a66a60921d5f/attendees?query=victor
